const {
  models: { Bank_Account, Transaction },
} = require("../db");

const categoryMap = {
  "Auto Insurance": 1,
  "Auto Payment": 2,
  "Gas & Fuel": 3,
  Parking: 4,
  "Public Transportation": 5,
  "Ride Share": 6,
  "Service & Parts": 7,
  "Home Phone": 8,
  Internet: 9,
  "Mobile Phone": 10,
  Television: 11,
  Utilities: 12,
  Subscription: 13,
  Advertising: 14,
  Legal: 15,
  "Office Supplies": 16,
  Printing: 17,
  Shipping: 18,
  "Books & Supplies": 19,
  "Student Loan": 20,
  Tuition: 21,
  Amusement: 22,
  Arts: 23,
  "Movies & DVDs": 24,
  "Newspapers & Magazines": 25,
  Entertainment: 26,
  "ATM Fee": 27,
  "Bank Fees": 28,
  "Finance Charge": 29,
  "Late Fee": 30,
  "Service Fee": 31,
  "Trade Commissions": 32,
  "Financial Advisor": 33,
  "Financial Planning and Investments": 34,
  "Life Insurance": 35,
  "Alcohol & Bars": 36,
  "Coffee Shops": 37,
  "Fast Food": 38,
  "Food Delivery": 39,
  Groceries: 40,
  Restaurants: 41,
  Charity: 42,
  Gift: 43,
  Dentist: 44,
  Doctor: 45,
  "Eye Care": 46,
  Gym: 47,
  "HealthCare Insurance": 48,
  Pharmacy: 49,
  Sports: 50,
  Furnishings: 51,
  "Home Improvement": 52,
  "Home Insurance": 53,
  "Home Services": 54,
  "Home Supplies": 55,
  "Lawn & Garden": 56,
  "Mortgage & Rent": 57,
  Bonus: 58,
  "Interest Income": 59,
  Paycheck: 60,
  Reimbursement: 61,
  "Rental Income": 62,
  "Rented Purchase": 63,
  Buy: 64,
  Deposit: 65,
  "Dividend & Cap Gains": 66,
  Sell: 67,
  Withdrawal: 68,
  Allowance: 69,
  "Baby Supplies": 70,
  "Baby Sitter & Daycare": 71,
  "Child Support": 72,
  "Kids Activities": 73,
  Toys: 74,
  "Loan Fees & Charges": 75,
  "Loan Insurance": 76,
  "Loan Interest": 77,
  "Loan Payment": 78,
  "Loan Principal": 79,
  Hair: 80,
  Laundry: 81,
  "Spa & Massage": 82,
  "Personal Care": 83,
  "Pet Food & Supplies": 84,
  "Pet Grooming": 85,
  Veterinary: 86,
  Pets: 87,
  Books: 88,
  "Clothing and Accessories": 89,
  "Electronics & Software": 90,
  "Arts and Crafts": 91,
  "Sporting Goods": 92,
  Auctions: 93,
  "Hardware Store": 94,
  Shops: 95,
  "Federal tax": 96,
  "Local Tax": 97,
  "Property Tax": 98,
  "Sales tax": 99,
  "State tax": 100,
  "Credit Card Payment": 101,
  Withdrawal: 102,
  Debit: 103,
  "Transfer For Cash Spending": 104,
  Travel: 105,
  "Air Travel": 106,
  Hotel: 107,
  "Rental Car & taxi": 108,
  Vacation: 109,
  Uncategorized: 110,
};

const plaidMap = {
  "Gas Stations": 0,
  Gas: 1,
  "Public Transportation Services": 2,
  "Car Parts and Accessories": 3,
  "Internet Services": 4,
  Cable: 5,
  Billpay: 6,
  "Business Services": 7,
  Bookstores: 8,
  Education: 9,
  "Arts and Crafts": 10,
  "Arts and Entertainment": 11,
  "Music, Video and DVD": 12,
  "Credit Counseling and Bankruptcy Services": 13,
  Financial: 14,
  "Coffee Shop": 15,
  "Supermarkets and Groceries": 16,
  "Convenience Store": 17,
  Food: 18,
  "Food and Beverage": 19,
  "Food and Drink": 20,
  "Gift and Novelty": 21,
  "Glasses and Optometrist": 22,
  "Gyms and Fitness Centers": 23,
  "Furniture and Home Decor": 24,
  "Keep the Change Savings Program": 25,
  "Loans and Mortgages": 26,
  "Beauty Products": 27,
  "Marine Supplies": 28,
  Clothing: 29,
  "Computers and Electronics": 30,
  Electronics: 31,
  "Department Stores": 32,
  "Digital Purchase": 33,
  "Discount Stores": 34,
  "Credit Card": 35,
  "Airlines and Aviation Services": 36,
  Lodging: 37,
  Taxi: 38,
  "Equipment Rental": 39,
};

const accountToDB = async (arr, arr2) => {
  for (let i = 0; i < arr.length; i++) {
    const bankAccount = await Bank_Account.create({
      account_id: arr[i].account_id,
      account_number: arr2.ach[i].account,
      account_type: arr[i].name,
      account_name: arr[i].official_name,
      available_balance: arr[i].balances.available,
      //using account_id, look up user with such account_id and assign userId to that user's ID
    });
  }
  console.log("seeding user success");
};

const transactionToDB = async (arr) => {
  for (let i = 0; i < arr.length; i++) {
    let credit = "debit";
    if (arr[i].amount < 0) {
      credit = "credit";
    }
    const transaction = await Transaction.create({
      account_id: arr[i].account_id,
      merchant: arr[i].name,
      date: arr[i].date,
      amount: arr[i].amount,
      category: arr[i].category[0],
      sub_category: arr[i].category[arr[i].category.length - 1],
      hide_from_budget: false,
      credit_debit: credit,
      //somehow do category
    });
  }
};

module.exports = { accountToDB, transactionToDB };
