const subcategoryArr = [
  " Auto Insurance",
  "Auto Payment",
  "Gas Stations",
  "Parking",
  "Public Transportation Services",
  "Ride Share",
  "Service & Parts",

  "Home Phone",
  "Internet",
  "Mobile Phone",
  "Cable",
  "Utilities",
  "Subscription",

  "Advertising",
  "Legal",
  "Office Supplies",
  "Printing",
  "Shipping",

  "Books & Supplies",
  "Student Loan",
  "Tuition",

  "Amusement",
  "Arts",
  "Music, Video and DVD",
  "Newspapers & Magazines",
  "Entertainment",

  "ATM Fee",
  "Bank Fees",
  "Finance Charge",
  "Late Fee",
  "Service Fee",
  "Trade Commissions",

  "Financial Advisor",
  "Financial Planning and Investments",
  "Life Insurance",

  "Alcohol & Bars",
  "Coffee Shop",
  "Fast Food",
  "Food Delivery",
  "Supermarkets and Groceries",
  "Convenience Store",
  "Food and Beverage",
  "Restaurants",

  "Charity",
  "Gift",

  "Dentist",
  "Doctor",
  "Eye Care",
  "Gyms and Fitness Centers",
  "HealthCare Insurance",
  "Pharmacy",
  "Sports",

  "Furnishings",
  "Home Improvement",
  "Home Insurance",
  "Home Services",
  "Home Supplies",
  "Lawn & Garden",
  "Mortgage & Rent",

  "Bonus",
  "Interest Income",
  "Paycheck",
  "Reimbursement",
  "Rental Income",
  "Rented Purchase",

  "Buy ",
  "Deposit",
  "Dividend & Cap Gains",
  "Sell",
  "Withdrawal",

  "Allowance",
  "Baby Supplies",
  "Baby Sitter & Daycare",
  "Child Support",
  "Kids Activities",
  "Toys",

  "Loan Fees & Charges",
  "Loan Insurance",
  "Loan Interest",
  "Loan Payment",
  "Loan Principal",

  "Hair",
  "Laundry",
  "Spa & Massage",
  "Personal Care",

  "Pet Food & Supplies",
  "Pet Grooming",
  "Veterinary",
  "Pets",

  "Books",
  "Clothing and Accessories",
  "Computers and Electronics",
  "Arts and Crafts",
  "Sporting Goods",
  "Auctions",
  "Hardware Store",
  "Shops",

  "Federal tax",
  "Local Tax",
  "Property Tax",
  "Sales tax",
  "State tax",

  "Credit Card",
  "Withdrawal",
  "Debit",
  "Transfer For Cash Spending",

  "Travel",
  "Airlines and Aviation Services",
  "Hotel",
  "Taxi",
  "Vacation",

  "Cash & ATM",
  "Check",
];
module.exports = subcategoryArr;
