const subcategoryArr = [
  "Auto Insurance",
  "Auto Payment",
  "Gas & Fuel",
  "Parking",
  "Public Transportation",
  "Ride Share",
  "Service & Parts",
  "Home Phone",
  "Internet",
  "Mobile Phone",
  "Television",
  "Utilities",
  "Subscription",
  "Advertising",
  "Legal",
  "Office Supplies",
  "Printing",
  "Shipping",
  "Books & Supplies",
  "Student Loan",
  "Tuition",
  "Amusement",
  "Arts",
  "Movies & DVDs",
  "Newspapers & Magazines",
  "Entertainment",
  "ATM Fee",
  "Bank Fees",
  "Finance Charge",
  "Late Fee",
  "Service Fee",
  "Trade Commissions",
  "Financial Advisor",
  "Financial Planning and Investments",
  "Life Insurance",
  "Alcohol & Bars",
  "Coffee Shops",
  "Fast Food",
  "Food Delivery",
  "Groceries",
  "Restaurants",
  "Charity",
  "Gift",
  "Dentist",
  "Doctor",
  "Eye Care",
  "Gym",
  "HealthCare Insurance",
  "Pharmacy",
  "Sports",
  "Furnishings",
  "Home Improvement",
  "Home Insurance",
  "Home Services",
  "Home Supplies",
  "Lawn & Garden",
  "Mortgage & Rent",
  "Bonus",
  "Interest Income",
  "Paycheck",
  "Reimbursement",
  "Rental Income",
  "Rented Purchase",
  "Buy",
  "Deposit",
  "Dividend & Cap Gains",
  "Sell",
  "Withdrawal",
  "Allowance",
  "Baby Supplies",
  "Baby Sitter & Daycare",
  "Child Support",
  "Kids Activities",
  "Toys",
  "Loan Fees & Charges",
  "Loan Insurance",
  "Loan Interest",
  "Loan Payment",
  "Loan Principal",
  "Hair",
  "Laundry",
  "Spa & Massage",
  "Personal Care",
  "Pet Food & Supplies",
  "Pet Grooming",
  "Veterinary",
  "Pets",
  "Books",
  "Clothing and Accessories",
  "Electronics & Software",
  "Arts and Crafts",
  "Sporting Goods",
  "Auctions",
  "Hardware Store",
  "Shops",
  "Federal tax",
  "Local Tax",
  "Property Tax",
  "Sales tax",
  "State tax",
  "Credit Card Payment",
  "Withdrawal",
  "Debit",
  "Transfer For Cash Spending",
  "Travel",
  "Air Travel",
  "Hotel",
  "Rental Car & taxi",
  "Vacation",
  "Cash & ATM",
  "Check",
  "Credit Card",
  "Debit Card",
];
module.exports = subcategoryArr;
